### ISSUE TITLE
Does this library work with Teensy 4.1?

### ISSUE THREAD

**Issue by smomid** [Richard-Gemmell/teensy4_i2c#13]
Hi, 

Does this library work with Teensy 4.1?

**Comment by Richard-Gemmell** [comment]
Hi,

Yes.

I haven't tried it myself but other people tell me that they've used it successfully with the 4.1.

cheers,
Richard

**Comment by smomid** [comment]
OK great thanks for the info.

**Comment by Richard-Gemmell** [comment]
You're welcome.
